### ISSUE TITLE
couchappignore is ignored

### ISSUE THREAD

**Issue by DoomyTheFroomy** [jo/couchdb-compile#19]
A couchapp directory normally contains a [`.couchappignore`](https://github.com/couchapp/couchapp/wiki/.couchappignore) file where all the not needed folders and files are mentioned. This also helps to prevent pushing an unsupported file type. It would be great to have something similar or to use the same file.

**Comment by wu-lee** [comment]
To second this request: as new user, this was almost the first problem I hit.  Many editors create backup files (like emacs, which uses the `~` suffix).  If not ignored, these get pushed (when used as part of couchdb-push), and/or create problems with the compilation process.

For example, my attempt to push suddenly started throwing a stack trace like, this, simply because I edited the `_id` file, creating an `_id~` backup:

    Error: Bad special document member: _id~
        at Request._callback (<root-dir>/node_modules/couchdb-push/node_modules/nano-option/node_modules/nano/lib/nano.js:234:15)
        at Request.self.callback (<root-dir>/node_modules/couchdb-push/node_modules/nano-option/node_modules/nano/node_modules/request/request.js:198:22)
        at Request.emit (events.js:98:17)
        at Request.<anonymous> (<root-dir>/node_modules/couchdb-push/node_modules/nano-option/node_modules/nano/node_modules/request/request.js:1035:10)
        at Request.emit (events.js:117:20)
        at IncomingMessage.<anonymous> (<root-dir>/node_modules/couchdb-push/node_modules/nano-option/node_modules/nano/node_modules/request/request.js:962:12)
        at IncomingMessage.emit (events.js:117:20)
        at _stream_readable.js:944:16
        at process._tickCallback (node.js:448:13)

Deleting the backup files is a workaround, but being able to ignore these files would be a more ideal solution.

**Comment by jo** [comment]
Totally see you point, thanks for the explanation.
